# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: documents.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64ocuments.proto\x12\tdocuments\"\x81\x01\n\x04Page\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x32\n\npage_value\x18\x02 \x03(\x0b\x32\x1e.documents.Page.PageValueEntry\x1a\x30\n\x0ePageValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xad\x01\n\x08Metadata\x12\x11\n\tfile_type\x18\x01 \x01(\t\x12\x15\n\rdocument_name\x18\x02 \x01(\t\x12@\n\x0f\x61\x64\x64itional_info\x18\x03 \x03(\x0b\x32\'.documents.Metadata.AdditionalInfoEntry\x1a\x35\n\x13\x41\x64\x64itionalInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"Q\n\x08\x44ocument\x12\x1e\n\x05pages\x18\x01 \x03(\x0b\x32\x0f.documents.Page\x12%\n\x08metadata\x18\x02 \x01(\x0b\x32\x13.documents.Metadata\"3\n\tDocuments\x12&\n\tdocuments\x18\x01 \x03(\x0b\x32\x13.documents.Documentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'documents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAGE_PAGEVALUEENTRY']._loaded_options = None
  _globals['_PAGE_PAGEVALUEENTRY']._serialized_options = b'8\001'
  _globals['_METADATA_ADDITIONALINFOENTRY']._loaded_options = None
  _globals['_METADATA_ADDITIONALINFOENTRY']._serialized_options = b'8\001'
  _globals['_PAGE']._serialized_start=31
  _globals['_PAGE']._serialized_end=160
  _globals['_PAGE_PAGEVALUEENTRY']._serialized_start=112
  _globals['_PAGE_PAGEVALUEENTRY']._serialized_end=160
  _globals['_METADATA']._serialized_start=163
  _globals['_METADATA']._serialized_end=336
  _globals['_METADATA_ADDITIONALINFOENTRY']._serialized_start=283
  _globals['_METADATA_ADDITIONALINFOENTRY']._serialized_end=336
  _globals['_DOCUMENT']._serialized_start=338
  _globals['_DOCUMENT']._serialized_end=419
  _globals['_DOCUMENTS']._serialized_start=421
  _globals['_DOCUMENTS']._serialized_end=472
# @@protoc_insertion_point(module_scope)
